[profile.default]
src = 'contracts'
out = 'artifacts'
libs = [
    'lib',
    'node_modules',
]
test = 'foundry-tests'
remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@solidity-parser/=node_modules/truffle-flattener/node_modules/@solidity-parser/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'forge-std/=lib/forge-std/src/',
    'hardhat-deploy/=node_modules/hardhat-deploy/',
    'hardhat/=node_modules/hardhat/',
]
gas_reports = ["*"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

verbosity = 3
fs_permissions = [{ access = "read", path = "./"}]
sender = "0x00a329c0648769a73afac7f9381e08fb43dbea72"

[fuzz]
max_test_rejects = 4_294_967_295   # 2^32 - 1
runs = 2048

[rpc_endpoints]
zkEra = "${ZKSYNC_NODE_URL}"

[etherscan]
